export type Issue = {
  titulo: string;
  usuario: string;
  setor: string;
  status: "aberto" | "andamento" | "resolvido" | "cancelado";
  prioridade: "baixa" | "media" | "alta";
  criado_em: string; // ISO date string
};

export const issues: Issue[] = [
  {
    titulo: "Erro no sistema de login",
    usuario: "Ana Santos",
    setor: "Tecnologia",
    status: "aberto",
    prioridade: "alta",
    criado_em: "2025-01-12 09:32:00",
  },
  {
    titulo: "E-mail corporativo não sincroniza",
    usuario: "Carlos Almeida",
    setor: "Recursos Humanos",
    status: "andamento",
    prioridade: "media",
    criado_em: "2025-01-11 15:20:00",
  },
  {
    titulo: "Problema na impressora do setor",
    usuario: "Juliana Ribeiro",
    setor: "Financeiro",
    status: "resolvido",
    prioridade: "baixa",
    criado_em: "2025-01-10 10:05:00",
  },
  {
    titulo: "Acesso negado ao dashboard",
    usuario: "Marcelo Silva",
    setor: "Tecnologia",
    status: "cancelado",
    prioridade: "alta",
    criado_em: "2025-01-12 08:11:00",
  },
  {
    titulo: "Computador não liga",
    usuario: "Renata Costa",
    setor: "Atendimento",
    status: "andamento",
    prioridade: "alta",
    criado_em: "2025-01-11 18:44:00",
  },
  {
    titulo: "Sistema travando ao abrir relatórios",
    usuario: "Gabriel Rocha",
    setor: "Financeiro",
    status: "aberto",
    prioridade: "alta",
    criado_em: "2025-01-10 11:25:00",
  },
  {
    titulo: "Erro ao enviar formulário",
    usuario: "Larissa Dias",
    setor: "Tecnologia",
    status: "andamento",
    prioridade: "media",
    criado_em: "2025-01-09 14:17:00",
  },
  {
    titulo: "Aplicação fechando inesperadamente",
    usuario: "João Mendes",
    setor: "Tecnologia",
    status: "resolvido",
    prioridade: "alta",
    criado_em: "2025-01-08 16:45:00",
  },
  {
    titulo: "Acesso lento ao sistema",
    usuario: "Beatriz Moura",
    setor: "Administrativo",
    status: "aberto",
    prioridade: "media",
    criado_em: "2025-01-07 09:30:00",
  },
  {
    titulo: "Erro ao autenticar usuário",
    usuario: "Fernando Oliveira",
    setor: "Tecnologia",
    status: "aberto",
    prioridade: "alta",
    criado_em: "2025-01-06 12:50:00",
  },
  {
    titulo: "Relatórios sem carregar dados",
    usuario: "Patricia Freitas",
    setor: "Financeiro",
    status: "andamento",
    prioridade: "alta",
    criado_em: "2025-01-05 10:12:00",
  },
  {
    titulo: "Impressora desconectando da rede",
    usuario: "Eduardo Ramos",
    setor: "Administrativo",
    status: "cancelado",
    prioridade: "baixa",
    criado_em: "2025-01-04 15:00:00",
  },
  {
    titulo: "Sistema não salva alterações",
    usuario: "Camila Silva",
    setor: "Atendimento",
    status: "resolvido",
    prioridade: "media",
    criado_em: "2025-01-03 11:44:00",
  },
  {
    titulo: "Painel de controle sem atualizar dados",
    usuario: "Thiago Nunes",
    setor: "Tecnologia",
    status: "aberto",
    prioridade: "alta",
    criado_em: "2025-01-02 07:20:00",
  },
  {
    titulo: "Falha ao fazer upload de arquivos",
    usuario: "Isabela Farias",
    setor: "Recursos Humanos",
    status: "andamento",
    prioridade: "media",
    criado_em: "2025-01-01 13:12:00",
  },
  {
    titulo: "Opção de filtro não funciona",
    usuario: "Diego Martins",
    setor: "Tecnologia",
    status: "aberto",
    prioridade: "baixa",
    criado_em: "2024-12-31 09:40:00",
  },
  {
    titulo: "Erro no carregamento da dashboard",
    usuario: "Manuela Santos",
    setor: "Administrativo",
    status: "andamento",
    prioridade: "alta",
    criado_em: "2024-12-30 14:10:00",
  },
  {
    titulo: "Formulário duplicando dados",
    usuario: "Ricardo Lima",
    setor: "Financeiro",
    status: "resolvido",
    prioridade: "media",
    criado_em: "2024-12-29 17:25:00",
  },
  {
    titulo: "Bloqueio inesperado de conta",
    usuario: "Helena Carvalho",
    setor: "Recursos Humanos",
    status: "aberto",
    prioridade: "alta",
    criado_em: "2024-12-28 10:55:00",
  },
  {
    titulo: "Erro na sincronização com o servidor",
    usuario: "Fábio Cunha",
    setor: "Tecnologia",
    status: "andamento",
    prioridade: "media",
    criado_em: "2024-12-27 08:32:00",
  },
];
